substitutions:
  # ESP - Badezimmer
  devicename: "esp32_4"
  upper_devicename: "ESP32 4"
  devicecomment: "Badezimmer - DHT"
  dht_gpio: "GPIO13"

<<: !include common/esp32.yaml

sensor:
  - !include common/ext-sensor-dht.yaml
