substitutions:
  # steckdose waschmaschine
  devicename: "esp32_1"
  upper_devicename: "ESP32 1"
  mac_address: !secret esp_home_mac_1

esphome:
  name: $devicename
  platform: esp32
  # board: esp01_1m
  # board: nodemcu-32s
  # board: sp32doit-devkit-v1
  # see: https://docs.platformio.org/en/latest/boards/espressif32/az-delivery-devkit-v4.html
  board: az-delivery-devkit-v4
  # on_boot:
  #   priority: 100
  #   then:
  #     - light.turn_on:
  #         id: dac_light1
  #         brightness: 10%

<<: !include common/base.yaml

# see: https://esphome.io/components/esp32_ble_tracker.html#on-ble-advertise
esp32_ble_tracker:

sensor:
  - !include common/base-sensor-wifi.yaml
  - !include common/base-sensor-uptime.yaml
  # see: https://esphome.io/components/sensor/xiaomi_ble.html?highlight=miflora#gcls002
  - platform: xiaomi_gcls002
    mac_address: "${mac_address}"
    temperature:
      name: "${devicename} Temperature"
    moisture:
      name: "${devicename} Moisture"
    conductivity:
      name: "${devicename} Soil Conductivity"
    illuminance:
      name: "${devicename} Illuminance"
    # does no longer work
    # battery_level:
    #   name: "${devicename} Battery Level"

# light:
#   - platform: monochromatic
#     name: "$upper_devicename LED"
#     output: gpio_19
#     id: dac_light1

# output:
#   - platform: ledc
#     pin: GPIO19
#     id: gpio_19
