substitutions:
  # steckdose drucker
  devicename: "gosund_sp111_3"
  upper_devicename: "Gosund SP111 3"
  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"
  # minimum wattage to mark consumer as active
  consumer_min_wattage: "10"

<<: !include common/gosund_sp111.yaml
