substitutions:
  # steckdose Keller Gefriertruhe
  devicename: "gosund_sp111_9"
  upper_devicename: "Gosund SP111 9"
  devicecomment: "Keller Gefriertruhe"
  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"
  # minimum wattage to mark consumer as active
  consumer_min_wattage: "6"
  # start on reboot
  boot_status: "on"
  boot_button: "button_switch"

<<: !include common/gosund_sp111.yaml
