substitutions:
  # steckdose waschmaschine
  devicename: "sonoff_pow_r2"
  upper_devicename: "Sonoff POW R2"
  devicecomment: "Keller Waschmaschine"
  # minimum wattage to mark consumer as active
  consumer_min_wattage: "10"

esphome:
  name: $devicename
  comment: $devicecomment
  on_boot:
    priority: -10
    then:
      - switch.turn_on: button_switch

esp8266:
  board: esp01_1m
  board_flash_mode: dout
  restore_from_flash: true

<<: !include common/base.yaml

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

binary_sensor:
  - !include common/ext-binary_sensor-consumer.yaml
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    # name: "${devicename} - Schalter Status"
    name: "Schalter Status"
    on_press:
      - switch.toggle: button_switch

sensor:
  - !include common/ext-sensor-wattage.yaml
  - !include common/ext-sensor-energy.yaml
  - !include common/ext-sensor-vcc.yaml
  - platform: cse7766
    # update_interval: 3s
    <<: !include common/param-power.yaml

switch:
  - platform: template
    # name: "${devicename} - Schalter"
    name: "Schalter"
    icon: mdi:power
    optimistic: true
    id: button_switch
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led_blue_hass
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led_blue_hass
  - platform: gpio
    id: relay
    pin: GPIO12

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: led_blue
    pin: GPIO13
    inverted: True

light:
  - !include common/ext-light-blue.yaml
