packages:
  web_server: !include base-web_server.yaml
  esphome: !include base-esphome.yaml
  wifi: !include base-wifi.yaml
  ota: !include base-ota.yaml
  sensor: !include base-sensor.yaml
  binary_sensor: !include base-binary_sensor.yaml
  text_sensor: !include base-text_sensor.yaml

# disable logging
logger:
  # disable logs
  baud_rate: 0
  # baud_rate: 115200
  level: INFO

# Enable Home Assistant API
api:
  # adds 2 additional components - ask to reconfigure in HA
  encryption:
    key: !secret api_encryption_key
  # reboot_timeout: 15
  # once home-assistant has added the device without passwords
  # it won't ask for a newly set password again
  # password: !secret api_password

# see: https://esphome.io/components/time.html
# time:
#   - platform: homeassistant
#     id: homeassistant_time
#     timezone: Europe/Vienna

# see: https://esphome.io/components/time/sntp.html
time:
  - platform: sntp
    timezone: "Europe/Vienna"
    id: sync_time
    servers:
      - 192.168.0.1
      - at.pool.ntp.org

# see: https://esphome.io/components/button/restart.html
button:
  - platform: restart
    # id: "${devicename}_restart"
    name: "${devicename} - Restart"