# Enable Web server
web_server:
  port: 80
  # webserver v3 is too big to include, will run over 50% flash limit
  # local: true
  auth:
    username: !secret api_username
    password: !secret api_password
  # see: https://esphome.io/components/web_server.html
  # css_include: "common/webserver-v1.min.css"
  # css_url: ""
  # js_include: "common/webserver-v1.min.js"
  # js_url: ""
  # see: https://esphome.io/components/web_server.html#here-be-dragons
  version: 3
  # js_include: "common/webserver-v2.min.js"
