<<: !include base.yaml

# see https://esphome.io/guides/configuration-types.html

packages:
  web_server: !include base-web_server.yaml
  esphome: !include base-esphome.yaml
  wifi: !include base-wifi.yaml
  ota: !include base-ota.yaml
  sensor: !include base-sensor.yaml
  binary_sensor: !include base-binary_sensor.yaml
  text_sensor: !include base-text_sensor.yaml
  bluetooth: !include base-ble.yaml

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino
    # type: esp-idf
    version: recommended

status_led:
  pin:
    number: GPIO02
    #inverted: True
    inverted: False
  id: led_blue
