<<: !include base.yaml

packages:
  web_server: !include base-web_server.yaml
  bluetooth: !include base-ble.yaml

esphome:
  name: $devicename
  comment: $devicecomment

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino
    version: recommended

binary_sensor:
  - !include base-binarysensor-status.yaml

sensor:
  - !include base-sensor-wifi.yaml
  - !include base-sensor-uptime.yaml

status_led:
  pin:
    number: GPIO02
    #inverted: True
    inverted: False
  id: led_blue
