esphome:
  name: $devicename
  platform: esp32
  # board: esp01_1m
  # board: nodemcu-32s
  # board: sp32doit-devkit-v1
  # see: https://docs.platformio.org/en/latest/boards/espressif32/az-delivery-devkit-v4.html
  board: az-delivery-devkit-v4
  # on_boot:
  #   priority: 100
  #   then:
  #     - light.turn_on:
  #         id: dac_light1
  #         brightness: 10%

<<: !include base.yaml

# see: https://esphome.io/components/esp32_ble_tracker.html#on-ble-advertise
esp32_ble_tracker:

sensor:
  - !include base-sensor-wifi.yaml
  - !include base-sensor-uptime.yaml

# light:
#   - platform: monochromatic
#     name: "$upper_devicename LED"
#     output: gpio_19
#     id: dac_light1

# output:
#   - platform: ledc
#     pin: GPIO19
#     id: gpio_19
