platform: total_daily_energy
# name: "${devicename} - Tagesverbrauch"
name: "Tagesverbrauch"
power_id: "power_wattage"
filters:
  # Multiplication factor from W to kW is 0.001
  - multiply: 0.001
unit_of_measurement: kWh
icon: mdi:calendar-clock
