<<: !include base.yaml

esphome:
  <<: !include param-boot_status.yaml
  name: $devicename
  comment: $devicecomment

esp8266:
  board: esp8285
  framework:
    version: recommended

# config from: https://community.home-assistant.io/t/gosund-sp111-with-esphome-power-measurement/194477

binary_sensor:
  # - !include ext-binary_sensor-status.yaml
  - !include ext-binary_sensor-consumer.yaml
  # switch relay off while holding
  # - platform: gpio
  #   id: button
  #   internal: true
  #   pin:
  #     number: GPIO13
  #   on_state:
  #     - switch.toggle: relay

  # toggle relay on/off
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    # name: "${devicename} - Schalter Status"
    id: "${devicename}_button_state"
    on_press:
      - switch.toggle: button_switch

sensor:
  - !include ext-sensor-wattage.yaml
  - !include ext-sensor-energy.yaml
  - !include ext-sensor-vcc.yaml
  # see pinout https://templates.blakadder.com/gosund_SP111_v1_1.html
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    # cf1_pin: GPIO14
    cf1_pin: GPIO04
    # see: https://esphome.io/components/sensor/hlw8012.html?highlight=change_mode_every
    change_mode_every: 4
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    update_interval: 3s
    <<: !include param-power.yaml

status_led:
  pin:
    number: GPIO02
    inverted: True
  id: led_blue

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led_red

switch:
  - platform: template
    name: "${devicename} - Schalter"
    icon: mdi:power
    optimistic: true
    id: button_switch
    turn_on_action:
      - switch.turn_on: relay
      # disable power led
      # - light.turn_on: led_red_hass
      # - output.turn_on: led_red
    turn_off_action:
      - switch.turn_off: relay
      # disable power led
      # - light.turn_off: led_red_hass
      # - output.turn_off: led_red

  - platform: gpio
    pin: GPIO15
    id: relay
    # icon: mdi:power-socket-eu
    # on_turn_on:
    #   - output.turn_on: led_red
    # on_turn_off:
    #   - output.turn_off: led_red
# light:
#   # ... and then make a normal light out of it.
#   - platform: binary
#     name: "${devicename} - LED (Red)"
#     output: led_red
#     id: led_red_hass
#     # icon: mdi:led-on
