# shamelessly copied from https://github.com/ferbar/esphome-configs/tree/main/config
effects:
  - addressable_random_twinkle:
      name: Random Twinkle
  - addressable_twinkle:
      name: Random Twinkle 5%
      twinkle_probability: 5%
      progress_interval: 12ms
  - addressable_random_twinkle:
      name: Random Twinkle 20%
      twinkle_probability: 20%
      progress_interval: 32ms
  - addressable_random_twinkle:
      name: Random Twinkle 80%
      twinkle_probability: 80%
      progress_interval: 32ms
  - addressable_scan:
      name: Scan
      move_interval: 300ms
      scan_width: 4
  - addressable_color_wipe:
      name: Color Wipe
  - addressable_rainbow:
      name: Rainbow
  - addressable_fireworks:
      name: Fireworks
      update_interval: 32ms
      spark_probability: 20%
      use_random_color: true
      fade_out_rate: 120

  - addressable_lambda:
      name: Christmas
      lambda: |-
        christmas(it);

  - addressable_lambda:
      name: Color change
      lambda: |-
        colorchange(it);

  - addressable_lambda:
      name: Random shift
      update_interval: 16ms
      lambda: |-
        randomshift(it);

  - addressable_lambda:
      name: Starry sky
      update_interval: 10ms
      lambda: |-
        starsLambda(it);

  - addressable_lambda:
      name: Candles
      update_interval: 16ms
      lambda: |-
        candles(it, initial_run);

  - addressable_lambda:
      name: Flicker
      update_interval: 16ms
      lambda: |-
        flicker(it, initial_run, current_color);

  # - addressable_lambda:
  #     name: "Wakeup"
  #     update_interval: 16ms
  #     lambda: |-
  #       wakeup(it, 60*15);

  # disable wled because nobody is using it
  # - wled:
  #     name: "wled"
  #     port: 19446
  - e131:
      # set with e131 on boot or by E1.31 in automations
      name: e131
      universe: 1
      channels: RGB
